---
# tasks file for postfix
- name: >
    Debian | set_fact
      postfix_supported_os: True
  set_fact:
    postfix_supported_os: True

- name: install postfix
  apt: pkg=postfix state=installed update_cache=yes cache_valid_time=86400
